name: nakacli
version: '0.1.1'
summary: CLI Client for Nakadi Edit
description: CLI Client for Nakadi Edit

grade: stable
confinement: strict
  
apps:
  nakacli:
    command: nakacli

parts:
  nakacli:
    build-packages:
      - pkg-config
      - libssl-dev
    plugin: rust
    source: https://github.com/amrhassan/nakacli.git
    source-tag: '0.1.1'
    rust-channel: nightly
